console.log("THIS IS A STRING");
let a="Sneha";
console.log(a);
console.log(a[0]);
console.log(a[1]);
console.log(a[2]);
console.log(a[3]);
console.log(a[4]);
console.log(a[5]); /*show undefined since it shows less error*/
console.log(a.length);
let name="Sneha";
let friends="Shivi";
console.log("name is "+name+" and friend name is "+friends);
console.log(`name is ${name} and friend name is ${friends}`);  /* ``->back tick */
let x=`Roh"an`;
console.log(x);
let y="Roh\nan";
console.log(y);
let z="Roh\"an";
console.log(z);
let e="Sneha";
console.log(e.toUpperCase());
console.log(e.toLowerCase());
console.log(e.length);
console.log(e.slice(1,4));
console.log(e.slice(1,8));
console.log(e.slice(2));
console.log(e.replace("Sn","N"));
let m="SnehaSneha";
console.log(m.replace("Sn","100"));
console.log(e.concat("99"));
console.log(e.concat(m));
let n="hello";
let o="every";
console.log(n.concat(o,"One"));
console.log(n.concat(o,"One","Two","Three"));
let p="    hello   everybody    ";
console.log(p);
console.log(p.trim());
console.log(p.trim());
let h="ONE,  T WO  , THREE";
console.log(h.split(","));
let s="Hello Everyone";
console.log(s.charAt(2));
console.log(s.charAt(50));
console.log(s.indexOf("ll"));
console.log(s.indexOf("la"));
console.log(s.startsWith("hello"));
console.log(s.startsWith("Hello"));
console.log(s.endsWith("one"));
console.log(s.endsWith("two"));